language: python
python:
  - 3.7
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install -U pytest-cov
  - pip install codecov
install:
  - pip install ".[test]" . # install package + test dependenci
services:
  - postgresql
before_script:
  - psql -c "CREATE DATABASE testing;" -U postgres
  - psql -c "CREATE USER foo WITH PASSWORD 'bar';" -U postgres
script: pytest # run tests
after_success:
  - codecov # submit coverage